CREATE DATABASE PLANI;
USE PLANI;

DROP TABLE  IF EXISTS PUEST;
CREATE TABLE PUEST (
COD_PUEST VARCHAR(10) NOT NULL,
NOM_PUEST VARCHAR(60) NOT NULL,
PRIMARY KEY(COD_PUEST)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE  IF EXISTS EMPL;
CREATE TABLE EMPL (
COD_EMPL VARCHAR(10) NOT NULL,
NOM_EMPL VARCHAR(60) NOT NULL,
SUEL_EMPL FLOAT(15),
COD_PUEST VARCHAR(10) NOT NULL,
COD_DEPAR VARCHAR(10) NOT NULL,
PRIMARY KEY(COD_EMPL),
CONSTRAINT FK_PUESTEMPL FOREIGN KEY (COD_PUEST) REFERENCES PUEST (COD_PUEST),
CONSTRAINT FK_DEPAREMPL FOREIGN KEY(COD_DEPAR) REFERENCES DEPAR (COD_DEPAR)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE  IF EXISTS DEPAR;
CREATE TABLE DEPAR (
COD_DEPAR VARCHAR(10) NOT NULL,
NOM_DEPAR VARCHAR(60) NOT NULL,
PRIMARY KEY(COD_DEPAR)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE  IF EXISTS ENCA_NOMI;
CREATE TABLE ENCA_NOMI (
COD_NOMI VARCHAR(5) NOT NULL,
FECHA_INI_NOMI VARCHAR(15) NOT NULL,
FECHA_FIN_NOMI VARCHAR(15) NOT NULL,
VAL_NOMI DOUBLE(10, 2),
PRIMARY KEY(COD_NOMI)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE  IF EXISTS DETALL_NOMI;
CREATE TABLE DETALL_NOM (
COD_NOMI VARCHAR(5) NOT NULL,
COD_EMPL VARCHAR(10) NOT NULL,
COD_CONCEP VARCHAR (10) NOT NULL,
VAL_NOMI_DET DOUBLE(10, 2),
PRIMARY KEY(COD_NOMI, COD_EMPL),
CONSTRAINT FK_ENCADETALLNOMI FOREIGN KEY(COD_NOMI) REFERENCES ENCA_NOMI (COD_NOMI),
CONSTRAINT FK_EMPLDETALLNOMI FOREIGN KEY(COD_EMPL) REFERENCES EMPL (COD_EMPL),
CONSTRAINT FK_CONCDETALLNOMI FOREIGN KEY(COD_CONCEP) REFERENCES CONCEPT (COD_CONCEP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE  IF EXISTS CONCEPT;
CREATE TABLE CONCEPT (
COD_CONCEP VARCHAR(10) NOT NULL,
NOM_CONCEP VARCHAR(60) NOT NULL,
EFEC_CONCEP VARCHAR(10) NOT NULL,
PRIMARY KEY(COD_conceptCONCEP)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE  IF EXISTS USUARIO;
CREATE TABLE USUARIO (
COD_USUARIO VARCHAR(10) NOT NULL,
NOM_USUARIO VARCHAR(60) NOT NULL,
CLAVE_USUARIO VARCHAR(10) NOT NULL,
COD_EMPL VARCHAR(10) NOT NULL,
PRIMARY KEY(COD_USUARIO),
CONSTRAINT FK_EMPLUSU FOREIGN KEY(COD_EMPL) REFERENCES EMPL (COD_EMPL)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
