package JFRAME;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NellyLlamileth
 */
public class PLANILLA extends javax.swing.JFrame {
public static String StrMatriz [][]= new String[10][11];
    public static Scanner Leer =new Scanner(System.in);//Declaramos un Scanner para que lea los dato.
    public  static int intSuelBas=0, intBoni=0, intComi=0, intDesJudi=0, intSuelLi1=0, intSuelLi2=0, intSuelLi3=0, intSuelLi4=0, intDep=0, intISR=0, intIGGS=0, intIGGS2=0 ;//Declaramos unas variables tipo entero para los calculos con numeros.
    public static String strSuelBas1, strBoni1, strComi1, strDesJudi1, strSuelLi8, strDep1, strIRS2, strIGGS2;//Declaramos unas variables String para poder mostrar
    public static double  dblISR1=0, dblIGGS1=0,dblSuelLi4=0, dblSuelLi5=0, dblSuelLi6=0, dblSuelLi7=0 ;//Declaramos variables tipo Double para la operaciones con punto decimal.
    /**
     * Creates new form PLANILLA
     */
    public PLANILLA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        GENE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "SUELDO_BAS", "BONIFICACION", "COMISION", "IGGS", "ISR", "DESCU_JUDI", "SUELDO_LIQ", "DEPARTAMENTO", "PUESTO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, 1030, 241));

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GENE.setText("GENERAR MATRIZ");
        GENE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENEActionPerformed(evt);
            }
        });
        jPanel1.add(GENE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 149, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("<<<<<PLANILLA>>>>>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CODIGO NOMINA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));
        jPanel1.add(CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("FECHA INICIAL:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));
        jPanel1.add(FF, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("FECHA FINAL:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));
        jPanel1.add(FI, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("POSICION DEL EMPLEADO: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));
        jPanel1.add(PE, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 130, -1));

        jButton1.setText("GENERAR NOMINA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 150, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CODIGO CONCEPTO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));
        jPanel1.add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GENEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENEActionPerformed
        String StrMat[][]= new String [10][11];
        StrMat = this.Mat();
        this.MakeMa(StrMat);
    }//GEN-LAST:event_GENEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int EMP=0,cont;
        EMP=Integer.parseInt(PE.getText());
        String StrCont;
        cont=Integer.parseInt(CC.getText());

        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/plani", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into detall_nom(COD_NOMI, COD_EMPL, COD_CONCEP, VAL_NOMI_DET)"+"values(?,(select COD_EMPL from empl where COD_EMPL=?),(select COD_CONCEP from concept where COD_CONCEP=?),?)");
            pst.setString(1, CN.getText().trim());
            pst.setString(2, StrMatriz[EMP][0].trim());
            pst.setString(3, CC.getText().trim());
            pst.setString(4, StrMatriz[EMP][cont].trim());
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null,"DETALLE BIEN.");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"DETALLE MAL");
        }
        
        
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/plani", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into enca_nomi(COD_NOMI, FECHA_INI_NOMI, FECHA_FIN_NOMI, VAL_NOMI)"+"values((select COD_NOMI from detall_nom where COD_NOMI = ?),?,?,?)");
            

            pst.setString(1, CN.getText().trim());
            pst.setString(2, FI.getText().trim());
            pst.setString(3, FF.getText().trim());
            pst.setString(4, StrMatriz[EMP][8].trim());
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null,"ENCA BIEN");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"ENCA MAL");
        }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PLANILLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PLANILLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PLANILLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PLANILLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PLANILLA().setVisible(true);
            }
        });
    }

   
    
    public void MakeMa(String StrMatriz[][]){
    DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
    mod.setRowCount(10);
    mod.setColumnCount(11);
    for(int Cont=0; Cont<10; Cont++){
       for(int Cont2=0; Cont2<11; Cont2++){
       jTable1.setValueAt(StrMatriz[Cont][Cont2], Cont, Cont2);
       
       }
     }
    }
    
   
    //er
  
    
    
    
    
    
    public String[][] Mat(){
        
        
        for(int intCont=0; intCont<10; intCont++){//Pedimos los codigos de los empleados
          StrMatriz[intCont][0]=JOptionPane.showInputDialog("Ingrese el codigo del Empleado en la posicion: ["+intCont+"] [0]");
        }
        
         System.out.println("\n");
        
        for(int intCont=0; intCont<10; intCont++){//Pedimos los Nombres de los empleados
          StrMatriz[intCont][1]=JOptionPane.showInputDialog("Ingrese el  Nombre del Empelado  en la posicion: ["+intCont+"] [1]");

        }
        
        System.out.println("\n");
        
        for(int intCont=0; intCont<10; intCont++){//Se ingresa un numero aleatorio en la variable entera
          intSuelBas=(int)(Math.random()*99000+1000);
          strSuelBas1= Integer.toString(intSuelBas);//Se vuelve String la varible entera           
          StrMatriz[intCont][2]=strSuelBas1;//Se Guarda en la Matriz
        }
        
        
        for(int intCont=0; intCont<10; intCont++){//Se ingresa un numero aleatorio en la variable entera
          intBoni=(int)(Math.random()*500+300);   
          strBoni1= Integer.toString(intBoni);//Se vuelve String la varible entera   
          StrMatriz[intCont][3]=strBoni1;//Se Guarda en la Matriz
        }
        
        
        for(int intCont=0; intCont<10; intCont++){//Se ingresa un numero aleatorio en la variable entera    
          intComi=(int)(Math.random()*500+300);
          strComi1= Integer.toString(intComi);//Se vuelve String la varible entera   
          StrMatriz[intCont][4]=strComi1;//Se Guarda en la Matriz
        }
        
        
        for(int intCont=0; intCont<10; intCont++){//Se usara if's para poder buscar en el suedlo base conforme a los rangos para sacarle su ISR
        intIGGS=Integer.parseInt(JOptionPane.showInputDialog("El Empelado en la posicion: ["+intCont+"] [0], ¿Pagará IGGS?: 1=SI 0=NO"));
      
        
        if(intIGGS==0){
        dblIGGS1= 0;
        }
        if(intIGGS==1){
        intIGGS2=Integer.parseInt(StrMatriz[intCont][2]);
        dblIGGS1= intIGGS2*0.0483;
        }
        strIRS2= String.valueOf((String.format("%.2f", dblIGGS1)));//Se vuelve String la varible double y que este dando unicamente 2 decimales
        StrMatriz[intCont][5]=strIRS2;//Se Guarda en la Matriz 
        }
        
        
    
        for(int intCont=0; intCont<10; intCont++){//Se usara if's para poder buscar en el suedlo base conforme a los rangos para sacarle su ISR
        intISR= Integer.parseInt(StrMatriz[intCont][2]);
        if(intISR<=5000){
        dblISR1= intISR*0.3;
        }
        if(intISR>=5001&&intISR<=10000){
        dblISR1= intISR*0.5;
        }
        if(intISR>=10001&&intISR<=100000){
        dblISR1= intISR*0.10;
        }
        strIRS2= String.valueOf((String.format("%.2f", dblISR1)));//Se vuelve String la varible double y que este dando unicamente 2 decimales
        StrMatriz[intCont][6]=strIRS2;//Se Guarda en la Matriz 
        }
        
        
        for(int intCont=0; intCont<10; intCont++){//Se ingresa un numero aleatorio en la variable entera    
          intDesJudi=(int)(Math.random()*500+300);
          strDesJudi1= Integer.toString(intDesJudi);//Se vuelve String la varible entera   
          StrMatriz[intCont][7]=strDesJudi1;//Se Guarda en la Matriz
        }
        
        
        for(int intCont=0; intCont<10; intCont++){
          intSuelLi1= Integer.parseInt(StrMatriz[intCont][2]);//Se toman los valores en dichas posiciones de la matriz para tomar su dato y convertirlo a enteros
          intSuelLi2= Integer.parseInt(StrMatriz[intCont][3]);
          intSuelLi3= Integer.parseInt(StrMatriz[intCont][4]);
          intSuelLi4= Integer.parseInt(StrMatriz[intCont][7]);
          dblSuelLi5= Double.parseDouble(StrMatriz[intCont][5]);//Se toman los valores en dichas posiciones de la matriz para tomar su dato y convertirlo a double
          dblSuelLi6= Double.parseDouble(StrMatriz[intCont][6]);
          dblSuelLi7= intSuelLi1+intSuelLi2+intSuelLi3-intSuelLi4-dblSuelLi5-dblSuelLi6;//Con los datos tomados de las posiciones anteriores se usaran para este calculo y se guarda en una variable String
          strSuelLi8= String.valueOf((String.format("%.2f", dblSuelLi7)));//Se vuelve String la varible double y que este dando unicamente 2 decimales
          StrMatriz[intCont][8]=strSuelLi8;//Se Guarda en la Matriz 
        }
        
        for(int intCont=0; intCont<10; intCont++){//Se ingresa un numero aleatorio en la variable entera  
          intDep=(int)(Math.random()*5+1);
          strDep1= Integer.toString(intDep);//Se vuelve String la varible entera 
          StrMatriz[intCont][9]=strDep1;//Se Guarda en la Matriz
         
        }
        
        for(int intCont=0; intCont<10; intCont++){//Se ingresa un numero aleatorio en la variable entera  
          intDep=(int)(Math.random()*5+1);
          strDep1= Integer.toString(intDep);//Se vuelve String la varible entera 
          StrMatriz[intCont][10]=strDep1;//Se Guarda en la Matriz
        }
        float fltVector[]= new float[5];//Se declara un vector tipo entero
        float fltD1=0,fltD2=0,fltD3=0,fltD4=0,fltD5=0, fltD6=0;//Se declaran varibales tipo entero como contadores para los departamentos
        for(int Cont=0; Cont<10; Cont++)//se Buscara en las posiciones de la matriz el #departamento para poder contabilizar cuantos empleados hay en cada departamento.
        {
        if(StrMatriz[Cont][9].equals("1")){
        fltD6=Float.parseFloat(StrMatriz[Cont][8]);
        fltVector[0]=fltD1=fltD1+fltD6;
        }
        if(StrMatriz[Cont][9].equals("2")){
        fltD6=Float.parseFloat(StrMatriz[Cont][8]);
        fltVector[1]=fltD2=fltD2+fltD6;
        }
        if(StrMatriz[Cont][9].equals("3")){
        fltD6=Float.parseFloat(StrMatriz[Cont][8]);
        fltVector[2]=fltD3=fltD3+fltD6;
        }
        if(StrMatriz[Cont][9].equals("4")){
        fltD6=Float.parseFloat(StrMatriz[Cont][8]);
        fltVector[3]=fltD4=fltD4+fltD6;
        }
        if(StrMatriz[Cont][9].equals("5")){
        fltD6=Float.parseFloat(StrMatriz[Cont][8]);
        fltVector[4]=fltD5=fltD5+fltD6;
        }
         }
        
        
        JOptionPane.showMessageDialog(null,"\n\nEmpleados en cada departamento:  \n"+
        "\n<<Departamento 1>>= "+fltVector[0]+//Se muestran los datos de cuantos empleados hay en cada departamento.
        "\n<<Departamento 2>>= "+fltVector[1]+
        "\n<<Departamento 3>>= "+fltVector[2]+
        "\n<<Departamento 4>>= "+fltVector[3]+
        "\n<<Departamento 5>>= "+fltVector[4]);
        
        
        for(int intCont=0; intCont<10; intCont++){
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/plani", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into empl(COD_EMPL, NOM_EMPL, SUEL_EMPL, COD_PUEST, COD_DEPAR)"+"values(?,?,?,(select COD_PUEST from puest where COD_PUEST = ?), (select COD_DEPAR from depar where COD_DEPAR = ?))");
            

            pst.setString(1, StrMatriz[intCont][0].trim());
            pst.setString(2, StrMatriz[intCont][1].trim());
            pst.setString(3, StrMatriz[intCont][2].trim());
            pst.setString(4, StrMatriz[intCont][10].trim());
            pst.setString(5, StrMatriz[intCont][9].trim());
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null,"Registro exitoso.");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Lastima.");
        }
        }
        
        
        return StrMatriz;
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CC;
    private javax.swing.JTextField CN;
    private javax.swing.JTextField FF;
    private javax.swing.JTextField FI;
    private javax.swing.JButton GENE;
    private javax.swing.JTextField PE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

















